name: Ian Arber - Composer
author: Ian Arber
myurl: https://www.ianarber.com
permalink: /:categories/:month/:year/:title/
future: true
vendor_react: react15.6.1.js

exclude:
  - attic
  - scripts
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - react
  - assets/script/modules/mobileMenu.js
  - assets/script/modules/quoteSlider.js
  - assets/script/modules/clientAreaAuth.js
  - assets/css/modules
  - assets/css/main.scss

collections:
  - quotes
  - listen
  - bioimages

# Make sure to export both these variables in your environment
# in order to authenticate to Contentful
# export CONTENTFUL_ACCESS_TOKEN=abc123
# export CONTENTFUL_SPACE_ID=abc123
contentful:
  spaces:
    - posts:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN