name: Ian Arber - Composer
author: Ian Arber
exclude: ["node_modules", "gulpfile.js", "package.json", ".brackets.json"]
cssToImport: main.min.css
myurl: https://ianarber.com
permalink: /:categories/:day/:month/:year/:title/