name: Ian Arber - Composer
author: Ian Arber
cssToImport: main.css
myurl: https://www.ianarber.com
permalink: /:categories/:month/:year/:title/
future: true

exclude:
  - attic
  - scripts
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - react
  - assets/script/modules/mobileMenu.js
  - assets/script/modules/quoteSlider.js
  - assets/script/modules/clientAreaAuth.js
  - assets/css/modules
  - assets/css/main.scss

collections:
  - quotes
  - bioimages

contentful:
  spaces:
    - posts:
        space: cn9cpn7kv7gw
        access_token: ada57850dcef0806293627506e55f63d9ba2cb00aa7e9b83aed85d06b70b97ad
